export const dbTableInfo = {
  UsersInfo:[
    { name: "id", type: "INTEGER", constrain: "PRIMARY KEY AUTOINCREMENT"},
    { name: "employeeid", type: "TEXT", constrain: "" },
    { name: "name", type: "TEXT", constrain: "" },
    { name: "jobtitle", type: "TEXT", constrain: "" },
    { name: "department", type: "INTEGER", constrain: "" },
    { name: "employmenttype", type: "TEXT", constrain: "" },
    { name: "office", type: "TEXT", constrain: "" },
    { name: "username", type: "TEXT", constrain: "" },
    { name: "password", type: "TEXT", constrain: "" },
    { name: "email", type: "TEXT", constrain: "" },
    { name: "address", type: "TEXT", constrain: "" },
    { name: "Varanasi", type: "TEXT", constrain: "" },
    { name: "created_time", type: "TEXT", constrain: "" },
    { name: "updated_date", type: "TEXT", constrain: "" },
    { name: "updated_time", type: "TEXT", constrain: "" },
    { name: "zoneid", type: "INTEGER", constrain: "" },
    { name: "wardid", type: "INTEGER", constrain: "" },
    { name: "screen_name", type: "TEXT", constrain: "" },
    { name: "profilePictureUrl", type: "TEXT", constrain: "" },
    { name: "created_date", type: "TEXT", constrain: "" },

  ],
 
  complainInfo:[
    { name: "offlineId", type: "INTEGER", constrain: "PRIMARY KEY AUTOINCREMENT"},
    { name: "id", type: "TEXT", constrain: "" },
    { name: "title", type: "TEXT", constrain: "" },
    { name: "time", type: "TEXT", constrain: "" },
    { name: "date", type: "TEXT", constrain: "" },
    { name: "status", type: "TEXT", constrain: "" },
    { name: "created_name", type: "TEXT", constrain: "" },
    { name: "assigned_date", type: "TEXT", constrain: "" },
    { name: "assigned_time", type: "TEXT", constrain: "" },
    { name: "task_start_date", type: "TEXT", constrain: "" },
    { name: "remarks", type: "TEXT", constrain: "" },
    { name: "task_end_date", type: "TEXT", constrain: "" },
    { name: "assignedby_name", type: "TEXT", constrain: "" },
    { name: "priority", type: "TEXT", constrain: "" },
    { name: "compintiateddate", type: "TEXT", constrain: "" },
    { name: "fields", type: "TEXT", constrain: "" },
  ],
  sync:[
    { name: "sync_id", type: "INTEGER", constrain: "PRIMARY KEY AUTOINCREMENT"},
    { name: "UsersInfo", type: "TEXT", constrain: "" },
    { name: "complainInfo", type: "TEXT", constrain: "" },
    { name: "userResponse", type: "TEXT", constrain: "" },
    { name: "DateTimeOfUpdate", type: "TEXT", constrain: "" },
  ]
}